name: PHPUnit with Database

on:
  push:
    branches:
      - dev
      - main
jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: payment_api
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo, pdo_mysql

      - name: Install Composer Dependencies
        run: composer install
        
      - name: Set up environment variables
        run: echo "$ENV_FILE" > .env
        
      - name: Show environment variables
        run: echo "$ENV_FILE" 
        
      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to start..."
          until nc -zv 127.0.0.1 3306
          do
            echo "MySQL is not ready yet, retrying in 5 seconds..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Run Database Migrations (if applicable)
        run: php bin/doctrine orm:schema-tool:update --force

      - name: Run PHPUnit Tests
        run: phpunit

